name: PHP Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test:
    name: PHP ${{ matrix.php-versions }} + ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-20.04', 'ubuntu-18.04']
        php-versions: ['7.4', '8.0']
        phpunit-versions: ['9.5']
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: pcov
        extensions: mbstring     
        tools: composer:v2, phpunit:9.5
    
    - name: Install Composer Dependencies
      run: composer install
    
    - name: Run Tests
      run: vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

    - name: Send coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: build/logs/clover.xml